name: panvimdoc

on:
  push:
    branches: [master]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: lipsum-nvim
          pandoc: "README.md"
          version: "NVIM v0.10.0"
          description: 'A "simple" Lorem Ipsum generation plugin.'
          toc: true
          dedupsubheadings: false
          treesitter: true
          demojify: true
          docmappingprojectname: false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
